# prefix C-aに変更する
set -g prefix C-a

# デフォルトのprefixキーC-bを解除する
unbind C-b

# prefix+\でペインを垂直分割する
bind v split-window -h -l 40%

# prefix+-でペインを水平分割する
bind s split-window -v

# 移動
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# 次・前のペイン
bind w select-pane -t :.+
bind b select-pane -t :.-

# Status Bar
set -g status-style bg=default,fg=#888888
set -g status-left ""
set -g status-right "#H %H:%M"
